eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
           - Path=/auth/**
          filters:
            - StripPrefix=1
#        - id: book-center-rpc    #路由 id,没有固定规则，但唯一，建议与服务名对应
#          uri: lb://light-reading-cloud-book  #动态路由，使用服务名代替上面的具体带端口
#          predicates:   #以下是断言条件，必选全部符合条件
#            - Path=/book/**   #断言，路径匹配 注意：Path 中 P 为大写
#            - Method=GET
server:
  port: ${PORT:8660}

logging:
  level:
    root: INFO
